name: Logation
description: Location logger plugin
author: AerenPozitif
main: aeren.logation.LogationMain
version: 1.0

commands:
  log:
    description: Logs a location with a name
    usage: For logging /<command> [location-name] \n For log list /<command> list

  deathlog:
    description: Shows your death history and locations
    usage: /<command>

  find:
    description: Finds logation
    usage: /<command> [logation-name]

  del:
    description: Deletes logation
    usage: /<command> [logation-name]

  tplog:
    description: Teleport to a logation
    usage: /<command> [logation-name]